image:
  repository: stakkato95/continuous-delivery-go
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  http:
    name: http
    port: 80

postgres_service:
  name: postgresql

ingress:
  enabled: true
